//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altairis.Xml4web.Importer.Nemesis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altairis.Xml4web.Importer.Nemesis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	A.ArticleId,
        ///	A.Title,
        ///	A.Abstract,
        ///	A.CategoryId, C.Name AS CategoryName,
        ///	A.AuthorId, U.Name AS AuthorName, U.Email AS AuthorEmail,
        ///	A.SerialId, S.Name AS SerialName,
        ///	A.DateCreated, A.DatePublished, A.DateUpdated,
        ///	A.AlternateUrl,
        ///	A.PictureData, A.PictureContentType, A.PictureWidth, A.PictureHeight,
        ///	A.Body
        ///FROM
        ///	Articles AS A
        ///	LEFT JOIN Categories AS C ON A.CategoryId = C.CategoryId
        ///	LEFT JOIN Authors AS U ON A.AuthorId = U.AuthorId
        ///	LEFT JOIN Serials AS S ON A.SerialId =  S.Seri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ArticleDump {
            get {
                return ResourceManager.GetString("ArticleDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dcterms:http://purl.org/dc/terms/
        ///dc:http://purl.org/dc/elements/1.1/
        ///np9:http://schemas.altairis.cz/Nemesis/Publishing/9/
        ///x4w:http://schemas.altairis.cz/Xml4web/PageMetadata/.
        /// </summary>
        public static string Namespaces {
            get {
                return ResourceManager.GetString("Namespaces", resourceCulture);
            }
        }
    }
}
